'use client';
import { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Loader2, FileText, Sparkles, Printer } from 'lucide-react';
import { toast } from 'sonner';

export default function ReportsPage() {
  const [report, setReport] = useState<string>('');
  const [ctx, setCtx] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [orgName] = useState<string>('Your workspace');

  async function generate() {
    setLoading(true);
    try {
      const r = await fetch('/api/cfo/report', { method: 'POST' });
      const d = await r.json();
      if (!r.ok) { toast.error(d.error || 'Report failed'); return; }
      setReport(d.markdown || ''); setCtx(d.context || null);
      toast.success('Report generated');
    } finally { setLoading(false); }
  }

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-4 md:p-8">
      <div className="no-print flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div><h1 className="text-2xl font-semibold tracking-tight md:text-[28px]">AI Financial Reports</h1><p className="text-sm text-muted-foreground">Board-meeting ready. Generate, then export as PDF via your browser’s print dialog.</p></div>
        <div className="flex gap-2">
          {report && <Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" /> Export PDF</Button>}
          <Button onClick={generate} disabled={loading}>{loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating…</> : <><Sparkles className="mr-2 h-4 w-4" /> Generate report</>}</Button>
        </div>
      </div>

      {!report && !loading && (
        <Card><CardContent className="flex flex-col items-center justify-center py-16 text-center">
          <FileText className="h-10 w-10 text-muted-foreground" />
          <p className="mt-3 font-medium">No report yet</p>
          <p className="text-sm text-muted-foreground">Click “Generate report” to produce an executive monthly summary.</p>
        </CardContent></Card>
      )}
      {loading && <Card><CardContent className="py-12 text-center text-sm text-muted-foreground"><Loader2 className="mx-auto h-5 w-5 animate-spin" /><p className="mt-3">The CFO is drafting your report…</p></CardContent></Card>}

      {report && (
        <div className="report-sheet">
          <header className="mb-8 flex items-center justify-between border-b pb-5">
            <div className="flex items-center gap-3">
              <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-foreground text-background">
                <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"><path d="M4 20 L20 4" /><path d="M4 4 L20 20" /><circle cx="12" cy="12" r="3" /></svg>
              </span>
              <div><p className="text-sm font-semibold tracking-tight">NexusAI CFO</p><p className="text-xs text-muted-foreground">Executive Financial Report — {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p></div>
            </div>
            <div className="text-right"><p className="text-xs uppercase tracking-wider text-muted-foreground">Prepared for</p><p className="text-sm font-medium">{orgName}</p></div>
          </header>
          {ctx && (
            <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
              <Tile label="Health" value={`${ctx.health.score}/100`} />
              <Tile label="Revenue (30d)" value={`$${Math.round(ctx.kpis.revenue30d).toLocaleString()}`} />
              <Tile label="Expenses (30d)" value={`$${Math.round(ctx.kpis.expenses30d).toLocaleString()}`} />
              <Tile label="Runway" value={ctx.kpis.runwayDays == null ? '∞' : `${ctx.kpis.runwayDays} d`} />
            </div>
          )}
          <article className="prose prose-sm max-w-none dark:prose-invert prose-headings:font-semibold prose-headings:tracking-tight prose-h2:mt-7 prose-h2:text-lg prose-h2:border-b prose-h2:pb-2 prose-p:leading-relaxed">
            <Md text={report} />
          </article>
          <footer className="mt-10 border-t pt-4 text-center text-[10px] uppercase tracking-wider text-muted-foreground">Generated by NexusAI CFO · Claude Sonnet 4.5 · Verify critical figures before acting.</footer>
        </div>
      )}

      <style jsx global>{`
        @media print {
          .no-print, aside, header.sticky { display: none !important; }
          body { background: white !important; }
          .report-sheet { box-shadow: none !important; border: none !important; padding: 0 !important; }
          main, .report-sheet { max-width: none !important; padding: 0 !important; }
        }
        .report-sheet { background: hsl(var(--card)); border: 1px solid hsl(var(--border)); border-radius: 16px; padding: 32px; }
        @media (min-width: 768px) { .report-sheet { padding: 48px; } }
      `}</style>
    </div>
  );
}
function Tile({ label, value }: { label: string; value: string }) {
  return <div className="rounded-xl border bg-muted/30 p-3"><div className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-lg font-semibold tabular-nums">{value}</div></div>;
}
function Md({ text }: { text: string }) {
  const lines = text.split('\n');
  const nodes: React.ReactNode[] = [];
  let i = 0; let key = 0;
  const isNumLine = (l: string) => /^\s*\d+\.\s/.test(l);
  const isBulletLine = (l: string) => /^\s*[-*]\s/.test(l);
  while (i < lines.length) {
    const line = lines[i];
    if (line.trim() === '') { i++; continue; }
    if (/^##\s/.test(line)) { nodes.push(<h2 key={key++}>{line.replace(/^##\s/, '')}</h2>); i++; continue; }
    if (/^#\s/.test(line)) { nodes.push(<h1 key={key++}>{line.replace(/^#\s/, '')}</h1>); i++; continue; }
    if (isNumLine(line)) {
      const items: string[] = [];
      while (i < lines.length) {
        if (isNumLine(lines[i])) { items.push(lines[i].replace(/^\s*\d+\.\s/, '')); i++; }
        else if (lines[i].trim() === '' && lines[i + 1] !== undefined && isNumLine(lines[i + 1])) { i++; }
        else break;
      }
      nodes.push(<ol key={key++}>{items.map((it, j) => <li key={j}><Inline t={it} /></li>)}</ol>);
      continue;
    }
    if (isBulletLine(line)) {
      const items: string[] = [];
      while (i < lines.length) {
        if (isBulletLine(lines[i])) { items.push(lines[i].replace(/^\s*[-*]\s/, '')); i++; }
        else if (lines[i].trim() === '' && lines[i + 1] !== undefined && isBulletLine(lines[i + 1])) { i++; }
        else break;
      }
      nodes.push(<ul key={key++}>{items.map((it, j) => <li key={j}><Inline t={it} /></li>)}</ul>);
      continue;
    }
    const para: string[] = [];
    while (i < lines.length && lines[i].trim() !== '' && !isNumLine(lines[i]) && !isBulletLine(lines[i]) && !/^#{1,2}\s/.test(lines[i])) { para.push(lines[i]); i++; }
    nodes.push(<p key={key++}><Inline t={para.join(' ')} /></p>);
  }
  return <>{nodes}</>;
}
function Inline({ t }: { t: string }) {
  const parts = t.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  return <>{parts.map((p, i) => p.startsWith('**') ? <strong key={i}>{p.slice(2, -2)}</strong> : p.startsWith('`') ? <code key={i}>{p.slice(1, -1)}</code> : <span key={i}>{p}</span>)}</>;
}
